Replace usage of __MACH__ with __APPLE__
It turns out that __MACH__ macro refer to the Mach kernel, which is also
used for GNU/Hurd. Prefer usage of macro __APPLE__ in this case.

This should solve the following compilation error:

lib/extras/time.cc:25:10: fatal error: mach/mach_time.h: No such file or directory

For reference:

* https://developer.apple.com/library/archive/documentation/Porting/Conceptual/PortingUnix/compiling/compiling.html#//apple_ref/doc/uid/TP40002850-SW13